person:
  user-name: huangxin
  boss: false
  birth: 1999/6/28
  age: 22
  pet:
    name: 湘湘
    weight: 4.77
  interests:
    - 篮球
    - 足球
    - 羽毛球
  animal:
    - 猫咪
  score:
    数据库: 95
    JAVA: 99
  salays: [4396,2800,443]

  allpets:
    sick:
      - {name: xiangxiang, weight: 4.77}
    health:
      - {name: dami,weight: 10.55}
      - {name: xiaomi ,weight: 9.85}
#spring:
#  mvc:
#    static-path-pattern: /res/**

#spring:
#  web:
#    resources:
#      static-locations: [classpath=/haha
spring:
  servlet:
    multipart:
      max-file-size:
        10000MB
      max-request-size:
        10000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 123456
    druid:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
        wall:
          enabled: true
        slf4j:
          enabled: true


      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
      web-stat-filter:
        url-pattern: /*
        enabled: true
      aop-patterns: com.example.springbootcore.*

  jdbc:
    template:
      query-timeout: 3
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml
#   全局配置文件与configuration冲突 只能写一个
  configuration:
    map-underscore-to-camel-case: true



