package com.example.springbootcore.bean;

public class EmpKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Wed May 18 11:38:35 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.did
     *
     * @mbg.generated Wed May 18 11:38:35 CST 2022
     */
    private Integer did;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Wed May 18 11:38:35 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Wed May 18 11:38:35 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.did
     *
     * @return the value of employee.did
     *
     * @mbg.generated Wed May 18 11:38:35 CST 2022
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.did
     *
     * @param did the value for employee.did
     *
     * @mbg.generated Wed May 18 11:38:35 CST 2022
     */
    public void setDid(Integer did) {
        this.did = did;
    }
}